### ISSUE TITLE
Podia ter um contraste da cor de fundo entre a navbar e as páginas do site pra diferenciar a navbar do body das páginas

### ISSUE THREAD

**Issue by cakemit** [cakemit/navcar#61]

**Comment by cakemit** [comment]
oi @luishenriquesimoes 
Eu comecei a colocar uma cor de fundo em alguns cards só pra dar uma diferenciada para o fundo branco da página mas acho que vou conflitar com seu trabalho nesse issue aqui... 

Vou desfazer o que eu fiz mas segue aqui a cor de fundo que poderia ser aplicada nos cards se vc achar que é válido:
style="background-color: #f7f7ef"

É um begezinho beeeeem clarinho

**Comment by luishenriquesimoes** [comment]
Como os cards estão cinzas e o fundo está branco, achei que a navbar cinza claro tb estava boa... se quiserem, posso diferenciar mais, mas fiquei com receio de mexer demais e ficar demais
